site_name: NumberScript Documentation
site_url: https://sas2k.github.io/NumberScript
nav:
  - Home: index.md
  - Setting Up/Getting Started: getting-started.md
  - Tutorial:
    - Basics: Tutorial/basics.md
    - Variables: Tutorial/Variables.md
    - If-Else: Tutorial/If-Else.md
  - About: about.md
theme:
  name: material
  logo: images/Logo.png
  favicon: images/Logo.png
  palette:
    primary: black
copyright: Copyright &copy 2022 <a href="https://github.com/Sas2k">Sas2k</a>